# Generated by Django 3.1.7 on 2021-02-26 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function_Collab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collab_name', models.CharField(max_length=255, verbose_name='FUNÇÃO')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('created_proj', models.DateTimeField(auto_now_add=True)),
                ('update_proj', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255)),
                ('created_st', models.DateTimeField(auto_now_add=True)),
                ('update_st', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collab_name', models.CharField(max_length=255, verbose_name='NOME DO COLABORADOR')),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/photos/', verbose_name='FOTO')),
                ('created_collab', models.DateTimeField(auto_now_add=True)),
                ('update_collab', models.DateTimeField(auto_now=True)),
                ('collab_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.function_collab', verbose_name='FUNÇÃO')),
                ('collab_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USUÁRIO')),
            ],
        ),
        migrations.CreateModel(
            name='Activity_All',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_comments', models.TextField()),
                ('activity_date_start', models.DateField(blank=True, null=True)),
                ('activity_date_prev', models.DateField(blank=True, null=True)),
                ('activity_date_end', models.DateField(blank=True, null=True)),
                ('created_ac', models.DateTimeField(auto_now_add=True)),
                ('update_ac', models.DateTimeField(auto_now=True)),
                ('activity_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.status', verbose_name='NOME')),
                ('collab_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.collab', verbose_name='NOME')),
            ],
        ),
    ]
